### ISSUE TITLE
Generating schema from TypedDict fails with ValueError

### ISSUE THREAD

**Issue by syastrov** [seandstewart/typical#12]
Cool library. It's nice to have a competitor to pydantic which seems a bit too loose for my taste. I was hoping I might be able to use it to:
- Coerce JSON data (as dicts) into TypedDicts rather than dataclasses and 
- Generate JSON schema from TypedDicts

(not sure if this is one of the goals of the project to make this work, but it seems like it fits in with the philosophy of this library as being unopinionated)

I tried the both, and they both fail. The latter fails with:

```python
>>> from typing_extensions import TypedDict
>>> class F(TypedDict):
...   a: str
...   b: int
... 
>>> typic.schema(F)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/.../venv/lib/python3.7/site-packages/typic/coercer.py", line 868, in schema
    annotation = self.resolve(obj)
  File "/.../venv/lib/python3.7/site-packages/typic/util.py", line 286, in _cached_method_wrapper
    result = func(*args, **kwargs)
  File "/.../venv/lib/python3.7/site-packages/typic/coercer.py", line 500, in resolve
    use, default=parameter.default, is_optional=is_optional
  File "/.../venv/lib/python3.7/site-packages/typic/coercer.py", line 430, in get_coercer
    return self._build_coercer(annotation, default=default, is_optional=is_optional)
  File "/.../venv/lib/python3.7/site-packages/typic/coercer.py", line 402, in _build_coercer
    self._build_mapping_coercer(func, args, anno_name)
  File "/.../venv/lib/python3.7/site-packages/typic/coercer.py", line 316, in _build_mapping_coercer
    key_type, item_type = args
ValueError: not enough values to unpack (expected 2, got 0)


# Same happens when it's wrapped in a dataclass
>>> from dataclasses import dataclass
>>> @typic.al
... @dataclass
... class Wrapper:
...   foo: str
...   bar: F
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/.../venv/lib/python3.7/site-packages/typic/api.py", line 184, in typed
    return _typed(_cls_or_callable) if _cls_or_callable is not None else _typed
  File "/.../venv/lib/python3.7/site-packages/typic/api.py", line 176, in _typed
    return wrap_cls(obj, delay=delay)  # type: ignore
  File "/.../venv/lib/python3.7/site-packages/typic/api.py", line 116, in wrap_cls
    coerce.annotations(klass)
  File "/.../venv/lib/python3.7/site-packages/typic/util.py", line 327, in _fast_cached_method_wrapper
    return memoget(arg)
  File "/.../venv/lib/python3.7/site-packages/typic/util.py", line 315, in __missing__
    self[key] = ret = func(instance, key)
  File "/.../venv/lib/python3.7/site-packages/typic/coercer.py", line 606, in annotations
    annotation, parameter=param, name=name, constraints=constraints
  File "/.../venv/lib/python3.7/site-packages/typic/util.py", line 286, in _cached_method_wrapper
    result = func(*args, **kwargs)
  File "/.../venv/lib/python3.7/site-packages/typic/coercer.py", line 500, in resolve
    use, default=parameter.default, is_optional=is_optional
  File "/.../venv/lib/python3.7/site-packages/typic/coercer.py", line 430, in get_coercer
    return self._build_coercer(annotation, default=default, is_optional=is_optional)
  File "/.../venv/lib/python3.7/site-packages/typic/coercer.py", line 402, in _build_coercer
    self._build_mapping_coercer(func, args, anno_name)
  File "/.../venv/lib/python3.7/site-packages/typic/coercer.py", line 316, in _build_mapping_coercer
    key_type, item_type = args
ValueError: not enough values to unpack (expected 2, got 0)

```

**Comment by seandstewart** [comment]
Hey @syastrov  - 

TypedDicts are a bit of a wart due to their implementation, but I've already paved a path toward implementing support. It's no good if it's causing the library to fail, however. I'll take a look and see about getting something implemented this week.

**Comment by seandstewart** [comment]
@syastrov the implementation was simpler than I expected, give the latest pre-release (v2.0.0b5) a try, it's been uploaded to pypi.

**Comment by syastrov** [comment]
Awesome, it works! 👍  thanks
