### ISSUE TITLE
duck example with enum does not works

### ISSUE THREAD

**Issue by hellozyemlya** [seandstewart/typical#53]
* typical version: master
* Python version: 3.7.7
* Operating System: ubuntu 18.04

### Description

Trying to run example from documentation.
```
import dataclasses
import datetime
import enum
import uuid

import typic

class DuckType(str, enum.Enum):
    WHT: "white"
    BLK: "black"
    MLD: "mallard"


@typic.al
@dataclasses.dataclass
class Duck:
    name: str
    type: DuckType
    created_on: datetime.datetime = dataclasses.field(
        default_factory=datetime.datetime.utcnow
    )
    id: uuid.UUID = dataclasses.field(
        default_factory=uuid.uuid4
    )
```
### What I Did
Imported module above, and observed followint traceback:
```
Traceback (most recent call last):
  File "/home/user/dev/test/blya.py", line 15, in <module>
    @dataclasses.dataclass
  File "/home/user/.local/lib/python3.7/site-packages/typic/api.py", line 367, in typed
    return _typed(_cls_or_callable) if _cls_or_callable is not None else _typed
  File "/home/user/.local/lib/python3.7/site-packages/typic/api.py", line 359, in _typed
    return wrap_cls(obj, delay=delay, strict=strict)  # type: ignore
  File "/home/user/.local/lib/python3.7/site-packages/typic/api.py", line 324, in wrap_cls
    wrapped: Type[WrappedObjectT] = cls_wrapper(klass)
  File "/home/user/.local/lib/python3.7/site-packages/typic/api.py", line 322, in cls_wrapper
    return _resolve_class(cls_, strict=strict, jsonschema=jsonschema, serde=serde)
  File "/home/user/.local/lib/python3.7/site-packages/typic/api.py", line 193, in _resolve_class
    protos = protocols(cls, strict=strict)
  File "/home/user/.local/lib/python3.7/site-packages/typic/serde/resolver.py", line 535, in protocols
    annotation, parameter=param, name=name, is_strict=strict
  File "/home/user/.local/lib/python3.7/site-packages/typic/serde/resolver.py", line 448, in resolve
    flags=flags,
  File "/home/user/.local/lib/python3.7/site-packages/typic/serde/resolver.py", line 379, in annotation
    if is_static
  File "/home/user/.local/lib/python3.7/site-packages/typic/serde/resolver.py", line 277, in _get_configuration
    for x, y in util.cached_type_hints(origin).items()
  File "/home/user/.local/lib/python3.7/site-packages/typic/util.py", line 375, in cached_type_hints
    return get_type_hints(obj)
  File "/usr/local/lib/python3.7/typing.py", line 978, in get_type_hints
    value = _eval_type(value, base_globals, localns)
  File "/usr/local/lib/python3.7/typing.py", line 263, in _eval_type
    return t._evaluate(globalns, localns)
  File "/usr/local/lib/python3.7/typing.py", line 467, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'white' is not defined
```

**Comment by seandstewart** [comment]
hey @hellozyemlya - thanks for submitting an issue!

This is actually an error with your enum declaration. It should read:

```python
import dataclasses
import datetime
import enum
import uuid

import typic

class DuckType(str, enum.Enum):
    WHT = "white"
    BLK = "black"
    MLD = "mallard"


@typic.al
@dataclasses.dataclass
class Duck:
    name: str
    type: DuckType
    created_on: datetime.datetime = dataclasses.field(
        default_factory=datetime.datetime.utcnow
    )
    id: uuid.UUID = dataclasses.field(
        default_factory=uuid.uuid4
    )
```

`WHT: "white"` gets registered as type annotations and `typical` tries to resolve them - which isn't possible.
